name: Android Release (Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "android/**"
      - "lib/**"
      - "pubspec.yaml"

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      # Fija una versión de Flutter estable para builds reproducibles.
      FLUTTER_VERSION: "3.22.2"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 (requerido por AGP 8.x)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter ${{ env.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Flutter doctor (debug rápido)
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      # ----- (Opcional) Firma: crea el keystore desde secretos -----
      - name: Prepare keystore
        if: env.ANDROID_KEYSTORE_BASE64 != ''
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          mkdir -p android/app/keystore
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/keystore/release.jks

      # ----- (Opcional) Firma: crea ~/.gradle/gradle.properties con credenciales -----
      - name: Configure signing props
        if: env.ANDROID_KEYSTORE_BASE64 != ''
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          mkdir -p ~/.gradle
          cat << 'EOF' >> ~/.gradle/gradle.properties
          MY_STORE_FILE=keystore/release.jks
          MY_STORE_PASSWORD=${ANDROID_KEYSTORE_PASSWORD}
          MY_KEY_ALIAS=${ANDROID_KEY_ALIAS}
          MY_KEY_PASSWORD=${ANDROID_KEY_PASSWORD}
          org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -Dkotlin.daemon.jvm.options=-Xmx2g
          android.useAndroidX=true
          android.enableJetifier=true
          EOF

      # ----- A) Build normal de release (usa cuando tengas AGP ≥ 8.1.1) -----
      - name: Build APK (release) - NORMAL
        if: ${{ false }} # pon esto a true cuando hayas subido AGP a 8.1.1+
        run: |
          # Si usas firma por gradle.properties + signingConfigs en tu app, no hace falta --no-shrink.
          flutter build apk --release --split-per-abi

      # ----- B) Build con bypass de validación (para saltar bloqueo AGP 8.1.0 vs 8.1.1) -----
      - name: Build APK (release) - BYPASS VALIDATION
        run: |
          flutter build apk --release --split-per-abi --android-skip-build-dependency-validation

      - name: Publica artefactos APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
