name: imaginaria_estudio
description: Starter nativo Flutter para IMAGINARIA ESTUDIO (Android listo; iOS listo para generar).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI y fuentes
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
  # WebView - versiones compatibles
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.1
  webview_flutter_wkwebview: ^3.13.0
  
  # Firebase - versiones estables actuales
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  
  # Notificaciones locales
  flutter_local_notifications: ^17.2.3
  
  # Compartir y links
  share_plus: ^10.0.2
  url_launcher: ^6.3.1
  
  # Storage y cache
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5
  
  # Utilidades
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/splash/

# Configuración de iconos
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon_1024.png"
  adaptive_icon_background: "#111827"

# Configuración de splash screen
flutter_native_splash:
  color: "#111827"
  image: assets/splash/splash_logo_512.png
  android_12:
    image: assets/splash/splash_logo_512.png
    icon_background_color: "#111827"
  android_gravity: center
  ios_content_mode: center
  web: false
