// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA59TwQF9-s4lymS326rItYi63SfKEHVlU',
    appId: '1:1081461024402:web:86ebb47edd6a04bd79284b',
    messagingSenderId: '1081461024402',
    projectId: 'app-android-6b3c4',
    authDomain: 'app-android-6b3c4.firebaseapp.com',
    storageBucket: 'app-android-6b3c4.firebasestorage.app',
    measurementId: 'G-P19PYFE67L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChWdGAMPROGpr7oPs792Pe7K7b5kevqBo',
    appId: '1:1081461024402:android:7edafdbbc6f8206c79284b',
    messagingSenderId: '1081461024402',
    projectId: 'app-android-6b3c4',
    storageBucket: 'app-android-6b3c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdUiX59h-YFFbXuGjCqLonQY1NYwZ6ktw',
    appId: '1:1081461024402:ios:0d05b3cb67b8e62e79284b',
    messagingSenderId: '1081461024402',
    projectId: 'app-android-6b3c4',
    storageBucket: 'app-android-6b3c4.firebasestorage.app',
    iosBundleId: 'com.imaginaria.imaginariaEstudio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdUiX59h-YFFbXuGjCqLonQY1NYwZ6ktw',
    appId: '1:1081461024402:ios:0d05b3cb67b8e62e79284b',
    messagingSenderId: '1081461024402',
    projectId: 'app-android-6b3c4',
    storageBucket: 'app-android-6b3c4.firebasestorage.app',
    iosBundleId: 'com.imaginaria.imaginariaEstudio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA59TwQF9-s4lymS326rItYi63SfKEHVlU',
    appId: '1:1081461024402:web:bfbdc52fab91984179284b',
    messagingSenderId: '1081461024402',
    projectId: 'app-android-6b3c4',
    authDomain: 'app-android-6b3c4.firebaseapp.com',
    storageBucket: 'app-android-6b3c4.firebasestorage.app',
    measurementId: 'G-EVPX3S396H',
  );
}
